### ISSUE TITLE
Tree.expandAll() doesn't exist

### ISSUE THREAD

**Issue by twh1808** [helion3/inspire-tree#10]
In following your bucket example, an `expandAll` method on the tree would be useful rather than iterating the nodes myself and ensuring they're expanded. Your example only expands based on the plucked ids you obtained, but that logic should probably live in an `expandAll` method for users to invoke.

**Comment by viveleroi** [comment]
Variants of `___All` methods exist, they're just not named *all*. Each collection of nodes is a TreeNodes object, which maps several methods to every TreeNode in the collection.

So to expand all nodes in a collection, use `tree.getNodes().expand()`. To expand all nodes recursively in a collection, use `tree.getNodes().expandDeep()`.

`tree.getNodes()` is really just the root collection, but these methods would work on any collection. So you could also do something like `tree.getNode('someId').getChildren().expand()`
