### ISSUE TITLE
How to make node editable on double click?

### ISSUE THREAD

**Issue by alirazaalvi** [helion3/inspire-tree#104]
I wanted to make tree node editable only on double click. How can i do that?

**Comment by viveleroi** [comment]
You can listen for the `node.dblclick` event.

By default, a double-click will expand the node, so if you want to toggle edit mode instead, I assume you don't want the native logic to fire. InspireTree provides a `preventTreeDefault` method so you can override the native logic:

```js
tree.on('node.dblclick', function(event, node) {
   event.preventTreeDefault();

    node.toggleEditing();
});
```

**Comment by alirazaalvi** [comment]
great. Thank you.
