### ISSUE TITLE
Inspire tree is not working in angular app 

### ISSUE THREAD

**Issue by SharpieX** [helion3/inspire-tree#105]
angular.js:13550 TypeError: _.defaultsDeep is not a function
    at new InspireTree (http://localhost:3000/bower_components/inspire-tree/dist/inspire-tree-core.js:143:26)

it is not able to loadsh function.

**Comment by viveleroi** [comment]
Either use `inspire-tree-core-bundled.js` or include [lodash](https://lodash.com) manually, ahead of inspire-tree `script` tag.
