### ISSUE TITLE
Tree.getAvailableNodes() returns nodes that are hidden/removed

### ISSUE THREAD

**Issue by twh1808** [helion3/inspire-tree#12]
Consider the following tree:

- Food
    + Fruit
        + Apple
        + Banana
        + Pear
    + Vegetables
        + Carrot
        + Tomato

I've `softRemove()`-ed Vegetables, so the node is *not* visible in the tree. If I run `Tree.getAvailableNodes()`, then Vegetables will be returned as a child of the Food node even though it's not technically available. Was the purpose of `Tree.getAvailableNodes()` to only return visible nodes? If so, I believe I've found an issue in the logic. If not, can I request a `Tree.getVisibleNodes()` method so I can know what the user considers part of the final *selection*.

**Comment by viveleroi** [comment]
The issue here is that `Food` is available, which passes the logic `getAvailableNodes` uses.  `getDeepestAvailableNodes` is sort of the opposite, it grabs from the *right*. It sounds like you want the entire structure, with only those available filtered?

**Comment by twh1808** [comment]
Yeah, essentially I want all nodes that are visible to the end user. I can get this data myself with some manipulation, but wanted to ask about a feature request before I did so.

**Comment by twh1808** [comment]
Rather than start a new issue, I will continue this thread since it's *slightly* related. The mapped `get___Nodes()` methods provide the ability to flatten the array but the root `getNodes()` does not. Can `getNodes()` provide flatten capabilities?

**Comment by viveleroi** [comment]
Are you sure? It forwards the arguments to the mapped method so they should work the same.

https://github.com/helion3/inspire-tree/blob/master/src/tree.js#L1570

**Comment by viveleroi** [comment]
I misread your comment. I can't think of any benefit flattening *all* nodes would have?

**Comment by twh1808** [comment]
I have no use for things that aren't a `leaf` in my tree, so I need to ignore all nodes that aren't leaves (for multiple things in the UI and logic execution). What I've done for getting available nodes is:
```
// Get all chosen leaf nodes (since this returns in a flattened state)
var selected = _.reject(tree.getAvailableNodes().export(), 'children');
```
Now for visual purposes I need to know what number of leaves were selected, whether that be `None`, `<Single Value>`, `Multiple`, or `All`, which is why I attempted to get all nodes as:
```
// Get every leaf ever available (currently broken because it's not flattened)
var leaves = _.reject(tree.getNodes().export(), 'children'):
```
Then I would run a comparison between `selected.length` and `leaves.length` to get the label values stated above. This is why I asked if the chain could consist of something like:
```
// Chain the methods to export only leaves
var leaves = srcTree.getNodes().leaves().export();
```
My tree(s) only "groups" leafs by different hierarchies, so those groups serve no purpose besides visual separation for the end user.

**Comment by viveleroi** [comment]
Does `deepest

**Comment by twh1808** [comment]
Yeah, `deepest` will work. It doesn't guarantee that node is a leaf so I am still running `.reject(tree.deepest().export(), 'children'):` but I'm fine with that solution.

Feel free to close/mark this issue however you'd like.

**Comment by viveleroi** [comment]
By `guarantee` do you mean it returns things that have `children: true`? If not, what do you mean?

**Comment by twh1808** [comment]
I should step back and state I was making an assumption.

I'm assuming in a dynamic tree instance, if I have `{ text: 'Apple', children: true }` (where children are nutritional facts), then `Apple` will be part of `deepest()` even though it's not a leaf.
