### ISSUE TITLE
Realtime updates, or refreshing the tree

### ISSUE THREAD

**Issue by enricribas** [helion3/inspire-tree#138]
Hello, thanks for the great project. 

I am trying to create a realtime updating tree with Vue and Firebase (though the how is irrelevant)
What is the best way to 'refresh' the data. 

If I use ```tree.load(data)``` on data changes, it creates duplicates even if nodes has ids, even if  I ```tree.clean()``` first.

If I initialize the tree with ```new InspireTree...``` and pass external reference to the data as in ``` data: window.someTreeData``` changing that object doesn't update the tree when I change that data, even if I resolve a promise. 

I know I must be missing something obvious but I'm stuck as to the best method to resolve this.

**Comment by enricribas** [comment]
I think I figured it out. Using tree.reload() after changing the external data reference. Thanks.

**Comment by viveleroi** [comment]
I'm not clear on what exactly you're doing, but triggering a reload to update data is very inefficient.

I'm not sure how Vue fits into this (if you're using it to render the Tree, none of what I'm about to say applies) but inspire tree will only update the DOM when it's told to and when there are recognized changes. If you're changing the text of a node, you can use [set](https://github.com/helion3/inspire-tree/blob/master/docs/treenode.md#set): `node.set('text', value);` That will mark the node as *dirty* which will be applied next time the dom updates.

If nothing else is happening in the tree (to trigger dom updates), you can manually apply the updates: `tree.dom.applyChanges();`

If you're dealing with lots of node updates at once, or nested changes, you can use the dom's batch/end methods for better performance.

I might be able to throw together a basic example if you clarify what you're trying.

**Comment by enricribas** [comment]
Thanks for the reply. 

Basically I'm just using Vue's "reactiveness" to control the data. So, I have some data object that is connected to Firebase so it might change externally so I don't know which node changes. I call 
```new InspireTree ... ``` with ```{ data: function (...) {resolve(vueDataObject)} } ```

Generally, vue notices when the data changes and renders. You can also listen to changes directly...
```watch: { vueDataObject: () => { doSomething() } }```
in my case the doSomething is where I call ```tree.reload()```

Unless I get Vue to do the tree rendering itself, not sure I can do anything other than call ```reload``` ??

**Comment by viveleroi** [comment]
Without knowing which node has changed, there's nothing more you can do really. `reload` clears the old data and re-imports it, which means everything is new and the tree fully re-renders. If you have consistent IDs on your nodes, you could at least write some custom "diff" logic but that's probably overkill for your needs.

**Comment by enricribas** [comment]
Cool, Thanks for your help!

**Comment by KrishnaPG** [comment]
Is there any example or package for Vue binding with this inspire-tree? Binding the data to tree and let it manage the updates through Vue reactivity will be great advantage.

**Comment by viveleroi** [comment]
We don't have any vue examples yet but there are react/inferno/angular examples which I'm sure you can draw from.
