### ISSUE TITLE
Incorrect search pagination

### ISSUE THREAD

**Issue by zant95** [helion3/inspire-tree#165]
When I set a pagination limit if no results were found on the first page the list is displayed empty. I think that pagination should be based solely on search results rather than all children.

### limit: 5
![](https://i.imgur.com/2O63S9b.png)

### limit: 2
![](https://i.imgur.com/jlLLefa.png)

### Code
```html
var tree = new InspireTree({
    pagination: { limit: 2 },
    data: $.getJSON('sample-data/full.json')
});

new InspireTreeDOM(tree, {
    target: '.tree',
    deferredRendering: true
});

$('input').on('keyup', _.debounce(function(event) {
    tree.search(this.value);
}, 500));
```
Example based on "[inspire-tree-dom/blob/master/demos/search.html](https://github.com/helion3/inspire-tree-dom/blob/7f861b0fdf96145154603b0f1e75602d7f84c288/demos/search.html)".

**Comment by viveleroi** [comment]
I moved this issue to the https://github.com/helion3/inspire-tree-dom/issues/2 repo. I've pushed a fix so it should work for you next release.
