### ISSUE TITLE
checked leaf node not automatically checking parent

### ISSUE THREAD

**Issue by steven-ferrer** [helion3/inspire-tree#171]
Hi, I was testing the inspire-tree checkbox feature and I thought there is an issue with not automatically checking the parent of a node when it set to be checked. 

On [this example repo](https://github.com/steven-ferrer/inspire-tree-example/tree/master) that I have created, I have set one node to be checked, but the parent is not automatically checked when the tree loads.

The current behavior is show on [this screenshot](https://github.com/steven-ferrer/inspire-tree-example/blob/master/current_behavior.png) and on the one hand, the expected behavior is shown on [this screenshot](https://github.com/steven-ferrer/inspire-tree-example/blob/master/expected_behavior.png), as when you click it, it should check the parent and highlight the checked node.

**Comment by viveleroi** [comment]
Nodes refresh their parent's indeterminate state when you call the API, `node.check()/uncheck()/etc` or when you toggle the DOM checkbox (and you're using inspire-tree-dom). Your example sets the checked state via the raw data node object, but you have no `indeterminate` set for the parent. The tree won't sanity check the incoming data, so you'll need to ensure it provides what's needed.

You have a few choices:
- Add the `indeterminate: true` to the parent node's object.
- Call `node.check()` manually after the `model.loaded` event.
- Write a helper that upon `model.loaded` recurses through all nodes and runs `refreshIndeterminateState`

**Comment by steven-ferrer** [comment]
@viveleroi, thank you very much for your prompt response.
