### ISSUE TITLE
Missing TypeScript definitions for NodeConfiguration

### ISSUE THREAD

**Issue by andy1547** [helion3/inspire-tree#175]

**Comment by viveleroi** [comment]
Can you clarify what you mean by `NodeConfiguration`? That sounds like an existing name but that isn't something used in our definitions file.

**Comment by andy1547** [comment]
I'm referring to the configuration objects used for creating nodes such as what's passed to InspireTree.addNode method, having a type would make life easier.

Currently trying to upgrade a legacy inspire-tree implementation (1.11) to the latest( 4.2.1), are there any major breaking changes I should be weary of or is most syntactic sugar? I assume this project follows semantic versioning?

**Comment by viveleroi** [comment]
v2 was a fairly large overhaul of the DOM rendering, but didn't much affect the API. Most of the other breaking changes are quite minor and may not even affect you depending on use.

Yes, this follows semver.

**Comment by viveleroi** [comment]
Also, you can read through the [changelog](https://github.com/helion3/inspire-tree/blob/master/CHANGELOG.md) for specifics.

I'll leave this open, as I should describe the node config object.
