### ISSUE TITLE
applyChanges is triggered twice on reload - via removeAll and after reload

### ISSUE THREAD

**Issue by viveleroi** [helion3/inspire-tree#186]
The reload function calls `removeAll()`, which calls `applyChanges`, which leads to re-render. A render is done anyway after `reload` has actually loaded nodes, leaded to a wasted render.

Originally mentioned in #184.

**Comment by andy1547** [comment]
I imagine this won't apply to master, but when I backported this change to v1.10.3 the DOM was no longer updated (the DOM did not update to reflex changes in text and added/removed nodes).

**Comment by viveleroi** [comment]
v1 was before the major DOM changes so I can't really say without diving in to fix things.
