### ISSUE TITLE
Few type errors

### ISSUE THREAD

**Issue by EnixCoda** [helion3/inspire-tree#187]
Hi,

I'm using version 5.0.2. and got few errors, please take a look. Thanks.

1. `data` is described as below in the `Tree Configuration` part of readme:
  `data - An array, promise, or callback function`.
But according to the `inspire-tree.d.ts` file, `data` has to be a function.

2. From `inspire-tree.d.ts` #L223:
`Property 'find' in type 'TreeNodes' is not assignable to the same property in base type 'TreeNode[]'.`

3. `TreeNode` seems missing `id`, `text` property definitions.

**Comment by viveleroi** [comment]
The last entry should be fixed by #190

**Comment by LuisAverhoff** [comment]
I'm using the latest version of inspire tree and so far the only type issue I'm getting is the following

```js
Property 'find' in type 'TreeNodes' is not assignable to the same property in base type 'TreeNode[]'.
  Type '(predicate: (node: TreeNode, index?: number | undefined, obj?: TreeNode[] | undefined) => boolean, thisArg?: any) => TreeNode' is not assignable to type '{ <S extends TreeNode>(predicate: (this: void, value: TreeNode, index: number, obj: TreeNode[]) => value is S, thisArg?: any): S | undefined; (predicate: (value: TreeNode, index: number, obj: TreeNode[]) => unknown, thisArg?: any): TreeNode | undefined; }'.
    Types of parameters 'predicate' and 'predicate' are incompatible.
      Types of parameters 'index' and 'index' are incompatible.
        Type 'number | undefined' is not assignable to type 'number'.
          Type 'undefined' is not assignable to type 'number'.

228     find(predicate: (node: TreeNode, index?: number, obj?: TreeNode[]) => boolean, thisArg?: any): TreeNode;
```

**Comment by viveleroi** [comment]
I plan on fully converting the codebase into typescript and modernizing it. I will address this kind of problem as I do that. I'll close this assuming this has to be fixed to v8 to launch.
