### ISSUE TITLE
Cursor drag in editing input while dragAndDrop=true starts drag

### ISSUE THREAD

**Issue by mkazar** [helion3/inspire-tree#189]
hi.
when dragAndDrop is true, in rename input, I cant select the text with mouse, correctly.

**Comment by mkazar** [comment]
hi.
when dragAndDrop is true, in rename input, I cant select the text with mouse, correctly.

**Comment by viveleroi** [comment]
This is an issue with the DOM rendering so I've moved it to the proper project.

I can reproduce it.
