### ISSUE TITLE
How to enhance performance for node.addChildren method (how to deferredRendering)

### ISSUE THREAD

**Issue by ryhn** [helion3/inspire-tree#193]
Hi,
if tree loaded once with tree.load(data) method, for large dataset pagination is working. But I need to add child nodes dynamically. I use node.addChildren() method with 15000 sample data. In that case, I can't figure out how to paginate or deferred loading.

Can you explain how pagination works for dynamically adding nodes

Thanks.

**Comment by viveleroi** [comment]
Pagination won't work this way, whatever you add through the API is what gets added. You should be building your data for the initial `load` call. If `children: true` and you're using a function/promise to load, those children will be loaded when necessary.
