### ISSUE TITLE
parent is auto selected (checked) when expanded

### ISSUE THREAD

**Issue by rlocus** [helion3/inspire-tree#194]
I use mode = 'checkbox', so when I expand a parent node the children (loaded dynamically) will select (deselect) automatically. So this is odd behaviour.

**Comment by viveleroi** [comment]
Please provide an example of the code you're using or better yet a reproduction somewhere I can see the defect. Expanding checkbox parent nodes on the demo site does not show this issue: http://www.inspire-tree.com/demos/checkboxes.html

**Comment by rpohomenko** [comment]
I use
inspire-tree
@version 6.0.1

But on the demo site is @version 5.0.0
Pls can you check the latest one? Thx

**Comment by viveleroi** [comment]
I setup a codepen using the latest version and dynamic loading (per your issue) and do not see the issue. Please take a look and see if you have anything I don't.

https://codepen.io/helion3/pen/wOYmYL

**Comment by rpohomenko** [comment]
I see, seems this is reproduced only on my dev site, anyway I solved this issue by refusing the checkboxes, thank you for your fast feedback.
