### ISSUE TITLE
"Cannot read property 'defaultsDeep' of undefined "

### ISSUE THREAD

**Issue by russellyoung** [helion3/inspire-tree#198]
I don't think I'm doing anything wrong: trying to use inspire-tree 6.0.1 gives the error in the subject on inspire-tree.js line 5433 ` _this.config = _.defaultsDeep({}, opts, {`, the variable `_` is null.

Here is the code which is making the call. I've substituted a very simple node in for the actual one. The error occurs in the `new InspireTree()` call.

```
		nodes = [{'text': 'asdasd'}];
		var tree = new InspireTree({data: nodes});
		new InspireTreeDOM(tree, {target: '#' + type + 'Tree'});
```

Am I maybe missing a file? I've tried it in 2 different browsers and after clearing cache. The last time I used inspireTree was version 1.7 so I'm a little out of practice.
```
  <head>
	<title>Tree test</title>
	<script src="js/inspire-tree.js"></script>
	<script src="js/inspire-tree-dom.js"></script>
	<script src="js/lodash.js"></script>
	<script src="js/client.js"></script>
  </head>
```
---

**Comment by viveleroi** [comment]
> the variable _ is null.

This means lodash isn't loading correctly.
