### ISSUE TITLE
Stop parent from being selected when all children are selected

### ISSUE THREAD

**Issue by bsansone** [helion3/inspire-tree#204]
Using the tree in a unique way where each "group" is also considered its own node, so just because all of its children are selected doesn't mean the group is selected. I'm aware of the option `autoCheckChildren` but kind of looking for something more like `autoCheckParent`, does this exist or is there a way I can write this on my end? Thank you!

**Comment by viveleroi** [comment]
This isn't possible currently. The only way you might be able to get it to work is by overriding either the `check` or `refreshIndeterminateState` methods on the `TreeNode` prototype. https://github.com/helion3/inspire-tree/blob/master/src/treenode.js#L199

That's responsible for calling the parent node and making it refresh it's checked/indeterminate status.

**Comment by bsansone** [comment]
@viveleroi Thanks for the insight, I'll look into possibly overriding those methods. Cheers.
