### ISSUE TITLE
Obsolete distribution

### ISSUE THREAD

**Issue by mjesteve** [helion3/inspire-tree#216]
Hi, I am still using this great library and I see that improvements have been made that I would like to have.
I can't manage to compile the project, I have dependency problems, could someone compile an updated distribution?

Thx.

**Comment by viveleroi** [comment]
What problems are you having? What version of node are you on?

**Comment by mjesteve** [comment]
Hi, this is the error report:
```
# npm resolution error report

While resolving: inspire-tree@7.0.0-beta.2
Found: rollup@3.26.2
node_modules/rollup
  dev rollup@"^3.26.2" from the root project

Could not resolve dependency:
peer rollup@">=0.60.0 <3" from rollup-plugin-babel@4.4.0
node_modules/rollup-plugin-babel
  dev rollup-plugin-babel@"^4.4.0" from the root project

Fix the upstream dependency conflict, or retry
this command with --force or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.
```
As you will see "I don't control too much js". When I have a little more time, I was thinking of looking at it because its resolution doesn't seem complicated, but now I can't spend too much time on it.

**Comment by viveleroi** [comment]
What command are you trying to run? `yarn build` works just fine for me.

**Comment by mjesteve** [comment]
No, I have never used yarn. I will try it.
Thank you.

**Comment by viveleroi** [comment]
This repository requires it.

**Comment by mjesteve** [comment]
It compiles but with errors. Doesn't it give you errors? It seems that there are circular dependencies:
```
$ rollup -c
(node:5000) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5000) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time

src\tree.js → build\inspire-tree.js...
(!) Circular dependencies
src/lib/collection-to-model.js -> src/lib/object-to-node.js -> src/lib/collection-to-model.js
src/lib/collection-to-model.js -> src/lib/object-to-node.js -> src/treenode.js -> src/lib/collection-to-model.js
src/lib/object-to-node.js -> src/treenode.js -> src/lib/object-to-node.js
...and 4 more
created build\inspire-tree.js in 2.6s
```

**Comment by viveleroi** [comment]
That's been a warning in the build output for some time but it's never had any impact on the build. Although I would like to rework the logic someday, it just hasn't been urgent
