### ISSUE TITLE
double click and drag-and-drop enhancements

### ISSUE THREAD

**Issue by russellyoung** [helion3/inspire-tree#32]
Here are a couple more minor changes that seem to me to be useful. If there are ways to do these now I couldn't find them, maybe they should be in a faq. If there aren't then maybe they could be added in the next version.

 - I want to use double click on a node for my own purposes. Setting up a handler for node.dblclick works fine, but the double click also toggles node expansion, which I don't want. I commented out the line that does that, but maybe it would be better to have that in its own node.dblclick handler so it could be removed without changing the source code.

 - I also want to drag and drop into other elements besides the tree. It turns out not to be too hard: I pass my elements in as dragTargets, add drop and allowdrop handlers to them, and make the following change in the source (line 12586):

Was:

	        if ($dragElement) {
	            if ($dragElement.parentNode) $dragElement.parentNode.removeChild($dragElement);

	            if ($activeDropTarget && $activeDropTarget.inspireTree) {
	                var newNode = $activeDropTarget.inspireTree.addNode($dragNode.copyHierarchy().export());

	                tree.emit('node.dropout', $dragNode, $activeDropTarget);
	                $activeDropTarget.inspireTree.emit('node.dropin', newNode);
	            }
	        }
change:

	        if ($dragElement) {
	            if ($dragElement.parentNode) $dragElement.parentNode.removeChild($dragElement);
				// rwy
	            if ($activeDropTarget) {
					if ($activeDropTarget.inspireTree) {
						var newNode = $activeDropTarget.inspireTree.addNode($dragNode.copyHierarchy().export());
						
						tree.emit('node.dropout', $dragNode, $activeDropTarget);
						$activeDropTarget.inspireTree.emit('node.dropin', newNode);
					}
					else
						tree.emit('drop', arguments[0], $dragNode, $activeDropTarget);
				}
	        }

**Comment by viveleroi** [comment]
The next version will include changes to address these issues.

First, you will be able to cancel our default dom events. When you invoke `preventTreeDefault` on the `event` argument, the tree will not execute the handler, so you can do whatever you like. However, the original handler is passed as third argument so if you still want to run it later, you can.

So if you need to prevent double clicks from opening the node:

```js
tree.on('node.dblclick', function(event, node, handler) {
    event.preventTreeDefault(); // Cancels default listener
    // do some custom logic
    handler(); // optionally call the original tree logic
});
```

This does have one breaking change though - these events are now called *before* the tree logic has run. It's likely not going to impact you but currently, the node object passed to the `node.dblclick` event would already show the results of the handler (`node.expanded()` would be true already). I may add a post-handler event someday for those who need that data still.

Secondly, you can now use any element as a drop target. The `node.dropout` event will always fire and the element it's dropped into is still passed as the second argument. For convenience, a new third argument is passed which tells you if that element is a tree instance or not. 

If the target *is* a tree, the `node.dropin` event fires. If the target is anything else, it won't.
