### ISSUE TITLE
Inline editing

### ISSUE THREAD

**Issue by viveleroi** [helion3/inspire-tree#5]
Nodes should allow inline editing, disabled by default.

- Some way to set a node to an edit state, with a cancel/save button.
- "cancel" restores the node text.
- "save" updates the `node.text` and fires a `node.edited` event with the new data.

**Comment by r3verser** [comment]
Hi, how the going with inline editing?:)

**Comment by viveleroi** [comment]
It's open for PR, I don't believe anyone's working on it yet. I might take it, but it isn't a high priority currently.

**Comment by enricribas** [comment]
Is there an event for 'node.edited' doesn't seem to be documented.

**Comment by viveleroi** [comment]
`node.edited` is not an existing event name, but I could add it. 

You could listen for the `node.state.changed` event, the event name would be `editing` and if it's changing from true -> false the editing has either been completed or canceled. Unfortunately there's no way to know if the text value has changed, since inspire tree doesn't track that for you.

**Comment by enricribas** [comment]
I was looking for an event to persist to db. 

```node.state.change``` works well enough. It happens too often but I can check 'property' for editing and oldValue is true. 

Strangely it seems like oldValue and newValue are not the values but booleans?

**Comment by viveleroi** [comment]
It's simple enough I can push an update later tonight with `node.edited`.

As for the state change event, the values are booleans because the event triggers when the node's state has changed - in this case the `editing` flag goes from false -> true when a user clicks the edit icon, and from true -> false when the user clicks save or cancel. "Value" doesn't refer to the node's text.

It does fire often, each node has a dozen potential states.

**Comment by enricribas** [comment]
That would be appreciated. It would be easier for me with a node.edited function. 

Thanks for your quick response. Really liking the tree view. I was using jstree before and getting really frustrated. :)

**Comment by viveleroi** [comment]
I found jstree impossible to work with, especially for an enterprise-level application.

**Comment by viveleroi** [comment]
Pushed 1.12.2 with a new `node.edited` event.

**Comment by enricribas** [comment]
amazing!! thanks!
