### ISSUE TITLE
Provide an example with Reactjs

### ISSUE THREAD

**Issue by aahmed-se** [helion3/inspire-tree#53]

**Comment by viveleroi** [comment]
I threw together a basic demo but it works better as a separate repo, which I should probably do for the angular demo too.

- Repo: https://github.com/helion3/inspire-tree-react-demo
- Demo: http://www.inspire-tree.com/react/

I used the new `create-react-app` module from the React team and just build a basic tree component.

**Comment by aahmed-se** [comment]
Thanks
