### ISSUE TITLE
drag and drop in the same tree

### ISSUE THREAD

**Issue by cherihung** [helion3/inspire-tree#6]
This tree component looks really great.
In the demo, the drag and drop is between two containers.
is there an example/way to drag nodes within the same tree? 
e.g. from one parent node to another.
thanks!

**Comment by viveleroi** [comment]
This has not yet been implemented, but it's something I would like to add eventually. It's been frequently solved by third party libraries though, so I'd like to do it in a way that can work with those and not reproduce the logic.

**Comment by cherihung** [comment]
very cool. 
do you have an example of how insipire-tree uses a 3rd-party lib to achieve this?

**Comment by viveleroi** [comment]
Inspire Tree does not offer drag-drop sorting. I would like to eventually, but rather than write custom code to handle it, it's a problem that's been solved by third party libraries so we'd likely find a way to integrate.

**Comment by cherihung** [comment]
great, i see. thank you.

**Comment by CMLL** [comment]
Has there been any change in this issue? Is this still a planned feature for Inspire Tree?

**Comment by viveleroi** [comment]
I would like to add it, but it's been such low priority I've been leaving it open for PRs. I have been toying with replacing our DOM rendering engine though, so if I were to take this on, it should wait until I've made a decision on that front.

**Comment by CMLL** [comment]
Thanks for the quick response. I'll pivot to a table based solution for my moving priority, and see if I can give a hand for this when I finish that.

**Comment by Zmove** [comment]
+1 for drag inside tree. With something simple like the editable option.

**Comment by etiennepinchon** [comment]
I wanted to use this library but without dragging it makes it kind of useless :( 
Hope you will add it one day ;)

**Comment by viveleroi** [comment]
This has been resolved by https://github.com/helion3/inspire-tree-dom/commit/4ef2015f81519e562755a26e919203ece52ac34c

It will be released with 3.0 soon.
