### ISSUE TITLE
wholerow takes extra space in IE

### ISSUE THREAD

**Issue by FraktalInverTer** [helion3/inspire-tree#63]
If placing the tree in an absolute positioned div with overflow auto, you will end up with unneccessary scrollbars in IE.

The last wholerow div in the tree sneaks in an extra 25px. Probably because IE handles the size calculation differently than chrome for example when it comes to the TranslateY trick.

Don't know if its a problem for anyone else but I thought you should know.
A fix would be most appreciated.
Leaving some simple repro code below:

```
<!DOCTYPE html>
<script src="inspire-tree-bundled.js"></script>
<link rel="stylesheet" type="text/css" href="inspire-tree.css">
<div style="overflow:auto;position:absolute;left:100px;top:100px;">
<div id="mytree"></div>
</div>
<script>
  new InspireTree({target: "#mytree", data:[{text:"Menu 1"},{text:"Menu 2"}]});
</script>
```

**Comment by viveleroi** [comment]
Which version(s) of IE?

**Comment by FraktalInverTer** [comment]
I noticed it on IE11. Just left work but I could test some other versions tomorrow and get back to you



Get Outlook for Android






On Wed, Sep 21, 2016 at 6:31 PM +0200, "Mike Botsko" <notifications@github.com> wrote:





Which version(s) of IE?
