### ISSUE TITLE
Spinner and checkbox cannot be on same node

### ISSUE THREAD

**Issue by onack** [helion3/inspire-tree#80]
If you use checkboxes it would be very nice if the spinner replaced the checkbox instead of being under it
Alternatively they could be side by side.
 
https://jsfiddle.net/3v5wL01u/2/

Thanks for the last fast response and fix

**Comment by viveleroi** [comment]
For my reference, here's a simpler reproduction: https://jsfiddle.net/2uncvjmf/1/
