### ISSUE TITLE
CSS styling got weird

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [helion3/inspire-tree#84]
Hi! It's me again. You were totally right about the lodash. Now is working!

But the CSS of it is a mess... What I'm doing wrong? I'm trying to fix it "brute force" way... but seams like a lot of things happening inside it.

<img width="283" alt="screen shot 2016-11-10 at 12 14 44 pm" src="https://cloud.githubusercontent.com/assets/346914/20186836/a3312690-a73f-11e6-8beb-fe849b1cc5d0.png">

<img width="292" alt="screen shot 2016-11-10 at 12 14 52 pm" src="https://cloud.githubusercontent.com/assets/346914/20186838/a69ae64a-a73f-11e6-8169-e2f9b61c15e9.png">

Any hint?

**Comment by patriciogonzalezvivo** [comment]
Sorry I didn't send a link to it: https://tangrams.github.io/ux_layers/#4/-24.97/-62.53 the source is here: https://github.com/tangrams/ux_layers

**Comment by viveleroi** [comment]
You have styling on the page that's also affecting the elements in the tree. For example styling for `.leaflet-bar a` is also affecting the tree anchors. You'll need to modify your UI css so that it's stricter/more self-contained.

**Comment by patriciogonzalezvivo** [comment]
`.leaflet-bar a` is set by Leaflet map engine and I don not have control over it. Any way to prevent their styling affecting inspire-tree ??

**Comment by viveleroi** [comment]
Not really, unfortunately. You can manually include a modified copy of the inspire-tree css that's more specific and can't be overridden, you can write custom css that reverses the "leaflet" css, you can try loading the tree in an iframe which won't share css from the parent document, but none of those are great options.

**Comment by patriciogonzalezvivo** [comment]
thanks again!
