### ISSUE TITLE
Browserify throws an error on core files for missing dom.js module

### ISSUE THREAD

**Issue by viveleroi** [helion3/inspire-tree#98]
Reported via https://github.com/helion3/inspire-tree-react-demo/issues/1

**Comment by alirazaalvi** [comment]
I installed inspire-tree 1.10.6 using npm but i am still getting the 'Cannot find module './dom' error. When i checked inspire-tree in node_modules folder there is no dom.js file in my dist folder. And  i am using browserify with gulp.

**Comment by alirazaalvi** [comment]
Yes it is working now. It was my mistake i added the 1.10.6 in the package.json but didn't ran the npm install again.  Thanks.
